all:
	gcc -c interface.c
	gcc -c isUserTaken.c
	gcc -c addUser.c
	gcc -c checkCredentials.c
	gcc -c saveWork.c
	gcc interface.o isUserTaken.o -o isUserTaken
	gcc interface.o addUser.o -o addUser
	gcc interface.o checkCredentials.o -o checkCredentials
	gcc interface.o saveWork.o -o saveWork
